import { existsSync, mkdirSync } from "node:fs";
import type { Connection, Schema } from "../../db/index.ts";
import { introspect } from "./introspect.ts";
import { tablesFromSchemas } from "./schema.ts";
import { renderInverseSql, renderSql } from "./sql.ts";
import type { DiffOp, DiffPlan, LiveColumn, LiveTable } from "./types.ts";

export type { DiffOp, DiffPlan, LiveColumn, LiveTable } from "./types.ts";

const colsByName = (cols: readonly LiveColumn[]): Map<string, LiveColumn> => new Map(cols.map((c) => [c.name, c]));

// `serial` is an integer + identity; an introspected DB always reports it as
// integer. Treat them as equivalent so `column.serial().primaryKey()` doesn't
// diff against a plain INTEGER PRIMARY KEY in SQLite.
const sameType = (a: LiveColumn, b: LiveColumn): boolean => {
  if (a.type === b.type) return true;
  const isIntLike = (t: string) => t === "serial" || t === "integer";
  return isIntLike(a.type) && isIntLike(b.type);
};

// SQLite reports `notnull = 0` for INTEGER PRIMARY KEY rowid aliases even
// though they're effectively NOT NULL. Compare nullability as `false` when
// the column is a primary key on either side.
const sameNullable = (a: LiveColumn, b: LiveColumn): boolean => {
  if (a.primary || b.primary) return true;
  return a.nullable === b.nullable;
};

const columnsEqual = (a: LiveColumn, b: LiveColumn): boolean =>
  sameType(a, b) && sameNullable(a, b) && a.primary === b.primary;

const diffTables = (live: readonly LiveTable[], desired: readonly LiveTable[]): DiffOp[] => {
  const ops: DiffOp[] = [];
  const liveMap = new Map(live.map((t) => [t.name, t]));
  const desiredMap = new Map(desired.map((t) => [t.name, t]));

  for (const t of desired) {
    if (!liveMap.has(t.name)) ops.push({ kind: "create_table", table: t });
  }

  for (const t of live) {
    if (!desiredMap.has(t.name)) ops.push({ kind: "drop_table", table: t });
  }

  for (const t of desired) {
    const existing = liveMap.get(t.name);
    if (!existing) continue;
    const liveCols = colsByName(existing.columns);
    const desiredCols = colsByName(t.columns);

    for (const c of t.columns) {
      const live = liveCols.get(c.name);
      if (!live) ops.push({ kind: "add_column", table: t.name, column: c });
      else if (!columnsEqual(live, c)) ops.push({ kind: "alter_column", table: t.name, from: live, to: c });
    }
    for (const c of existing.columns) {
      if (!desiredCols.has(c.name)) ops.push({ kind: "drop_column", table: t.name, column: c });
    }
  }

  return ops;
};

// Compute the diff between live DB state and the desired schemas.
// Does not write to disk — call writeDiff() to materialize.
export const plan = async (db: Connection, schemas: readonly Schema[]): Promise<DiffPlan> => {
  const live = await introspect(db);
  const desired = tablesFromSchemas(schemas);
  const ops = diffTables(live, desired);
  return {
    ops,
    up: renderSql(ops, db.dialect),
    down: renderInverseSql(ops, db.dialect),
  };
};

export type DiffOptions = {
  readonly name?: string;
  readonly dir?: string;
};

const timestamp = (): string => {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
};

export type DiffWriteResult = {
  readonly applied: false;
  readonly noop: boolean;
  readonly path: string | null;
  readonly plan: DiffPlan;
};

// Materialize the diff as a new migration directory with up.sql / down.sql.
// Returns { noop: true, path: null } if there's nothing to write.
export const writeDiff = async (
  db: Connection,
  schemas: readonly Schema[],
  opts: DiffOptions = {},
): Promise<DiffWriteResult> => {
  const computed = await plan(db, schemas);
  if (computed.ops.length === 0) {
    return { applied: false, noop: true, path: null, plan: computed };
  }
  const dir = opts.dir ?? "./migrations";
  const name = opts.name ?? "diff";
  const folderName = `${timestamp()}_${name}`;
  const target = `${dir}/${folderName}`;
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  mkdirSync(target, { recursive: true });

  const banner = "-- generated by `migrate diff` — review before running\n\n";
  await Bun.write(`${target}/up.sql`, `${banner}${computed.up}\n`);
  await Bun.write(`${target}/down.sql`, `${banner}${computed.down}\n`);

  return { applied: false, noop: false, path: target, plan: computed };
};
