CREATE TABLE likes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL REFERENCES users(id),
  postId INTEGER NOT NULL REFERENCES posts(id),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(userId, postId)
);
