import { afterEach, beforeEach, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { column, connect, defineSchema } from "../../db/index.ts";
import { plan as diffPlan, writeDiff } from "../diff/index.ts";

let workDir: string;

beforeEach(() => {
  workDir = mkdtempSync(`${tmpdir()}/atlas-diff-`);
});

afterEach(() => {
  rmSync(workDir, { recursive: true, force: true });
});

test("diff against an empty DB plans CREATE TABLE for every schema", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  const users = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text().unique(),
    bio: column.text().nullable(),
  });

  const result = await diffPlan(db, [users]);
  expect(result.ops).toHaveLength(1);
  expect(result.ops[0]?.kind).toBe("create_table");
  expect(result.up).toContain("CREATE TABLE users");
  expect(result.up).toContain("id INTEGER PRIMARY KEY");
  expect(result.up).toContain("email TEXT NOT NULL");
  expect(result.up).toContain("bio TEXT");
  expect(result.up).not.toContain("bio TEXT NOT NULL");
  expect(result.down).toContain("DROP TABLE users");

  await db.close();
});

test("diff detects added columns", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({ text: "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL)", values: [] });

  const users = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
    name: column.text().nullable(),
  });

  const result = await diffPlan(db, [users]);
  expect(result.ops).toHaveLength(1);
  expect(result.ops[0]).toMatchObject({ kind: "add_column", table: "users" });
  expect(result.up).toContain("ALTER TABLE users ADD COLUMN name TEXT");
  expect(result.down).toContain("ALTER TABLE users DROP COLUMN name");

  await db.close();
});

test("diff detects dropped columns and dropped tables", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({
    text: "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL, deprecated TEXT)",
    values: [],
  });
  await db.execute({ text: "CREATE TABLE legacy (id INTEGER PRIMARY KEY)", values: [] });

  const users = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
  });

  const result = await diffPlan(db, [users]);
  const kinds = result.ops.map((o) => o.kind).sort();
  expect(kinds).toEqual(["drop_column", "drop_table"]);
  expect(result.up).toContain("ALTER TABLE users DROP COLUMN deprecated");
  expect(result.up).toContain("DROP TABLE legacy");

  await db.close();
});

test("diff detects type/nullability mismatches as comments", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({ text: "CREATE TABLE t (id INTEGER PRIMARY KEY, count TEXT)", values: [] });

  const t = defineSchema("t", {
    id: column.serial().primaryKey(),
    count: column.integer(),
  });

  const result = await diffPlan(db, [t]);
  expect(result.ops).toHaveLength(1);
  expect(result.ops[0]?.kind).toBe("alter_column");
  expect(result.up).toContain("-- ALTER t.count");
  expect(result.up).toContain("type text → integer");

  await db.close();
});

test("diff against in-sync DB is a no-op", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({ text: "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL)", values: [] });

  const users = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
  });

  const result = await diffPlan(db, [users]);
  expect(result.ops).toEqual([]);
  expect(result.up).toBe("");

  await db.close();
});

test("writeDiff materializes a migration folder", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  const users = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
  });

  const result = await writeDiff(db, [users], { dir: workDir, name: "add_users" });
  expect(result.noop).toBe(false);
  expect(result.path).not.toBeNull();
  expect(existsSync(`${result.path}/up.sql`)).toBe(true);
  expect(existsSync(`${result.path}/down.sql`)).toBe(true);

  const up = readFileSync(`${result.path}/up.sql`, "utf-8");
  expect(up).toContain("CREATE TABLE users");
  expect(up).toContain("generated by `migrate diff`");

  await db.close();
});

test("writeDiff is a no-op when nothing changed", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({ text: "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL)", values: [] });

  const users = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
  });

  const result = await writeDiff(db, [users], { dir: workDir });
  expect(result.noop).toBe(true);
  expect(result.path).toBeNull();

  await db.close();
});

test("writeDiff produces distinct folders on successive runs", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  const usersV1 = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
  });

  const first = await writeDiff(db, [usersV1], { dir: workDir, name: "init" });
  expect(first.noop).toBe(false);
  expect(first.path).not.toBeNull();

  // Apply v1 manually so the live DB now matches usersV1.
  await db.execute({ text: "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL)", values: [] });

  // Add a column → second diff should write a new folder.
  const usersV2 = defineSchema("users", {
    id: column.serial().primaryKey(),
    email: column.text(),
    name: column.text().nullable(),
  });
  // Sleep is unnecessary — the timestamp uses seconds-resolution; if the test
  // runs fast enough to share a second, we still want different folder names.
  // Pass a different `name` to guarantee uniqueness regardless of timing.
  const second = await writeDiff(db, [usersV2], { dir: workDir, name: "add_name" });
  expect(second.noop).toBe(false);
  expect(second.path).not.toBe(first.path);
  expect(existsSync(`${second.path}/up.sql`)).toBe(true);

  await db.close();
});

test("nullable columns without explicit defaults don't trigger spurious diffs", async () => {
  // Live: column.text() with no DEFAULT; schema: same. Should be a no-op even
  // though one path tracks `hasDefault: false` and the other might not.
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({
    text: "CREATE TABLE t (id INTEGER PRIMARY KEY, note TEXT)",
    values: [],
  });

  const t = defineSchema("t", {
    id: column.serial().primaryKey(),
    note: column.text().nullable(),
  });

  const result = await diffPlan(db, [t]);
  expect(result.ops).toEqual([]);

  await db.close();
});

test("internal tables (schema_migrations, sqlite_*) are ignored", async () => {
  const db = connect({ driver: "sqlite", path: ":memory:" });
  await db.execute({
    text: "CREATE TABLE schema_migrations (name TEXT PRIMARY KEY, applied_at TIMESTAMP)",
    values: [],
  });
  await db.execute({ text: "CREATE TABLE users (id INTEGER PRIMARY KEY)", values: [] });

  const users = defineSchema("users", { id: column.serial().primaryKey() });
  const result = await diffPlan(db, [users]);
  expect(result.ops).toEqual([]);

  await db.close();
});
